#!/bin/bash -l
#SBATCH --job-name=animate
#SBATCH --account=uzh8
#SBATCH --mail-type=ALL
#SBATCH --mail-user=johannes.lade@uzh.ch
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=mc

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

dir='../output/output-high'

command="srun python animate.py -d=${dir} -n=${SLURM_NTASKS_PER_NODE}"
echo ${command}
eval ${command}
